@startuml TextAdventure Class Diagram
package es.hugoalvarezajenjo.textadventure {
    package model {
        class Player {
            - health: int
            - weapon: Weapon
            + new(health: int, weapon: Weapon): Player
        }

        abstract Weapon{
            - name: String
            - damage: int
            + new(name: String, damage: int): Weapon
        }

        class Knife {
            + new(): Knife
        }
        class LongSword {
            + new(): LongSword
        }

        class Story {
            - title: String
            - choice1: String
            - choice2: String
            - choice3: String
            - choice4: String
            + new(title: String, choice1: String, choice2: String, choice3: String, choice4: String): Story
        }
    }

    package logic {
        class PlayerManager <<controller>>{
            - player: Player
            + new(): PlayerManager
            + getPlayerHealth(): int
            + getPlayerWeaponName(): String
        }

        class StoryManager <<controller>> {
            - story: Story
            + new(): StoryManager
            + getStoryTitle(): String
            + getStoryChoices(): String[]
        }
    }

    package ui {
        class MainWindow <<UI>>
        class MainWindowController <<UIController>>
        abstract WindowScreen <<UI>>

        package startscreen {
            class StartScreen <<UI>>
            class StartButtonListener <<ViewListener>>
        }

        package choicescreen {
            class ChoiceScreen <<UI>> {
                + setHp(hp: int)
                + setWeaponName(weaponName: WeaponName)
                + setStoryTitle(title: String)
                + setStoryChoices(choice: String[])
            }
            class ChoiceScreenController <<UIController>> {
                - choicescreen: ChoiceScreen
                - updateHp(hp: int)
                - updateWeaponName(weaponName: WeaponName)
                - updateStoryTitle(title: String)
                - updateStoryChoices(choice: String[])
                - updateStory()
            }
            class ChoiceButtonListener <<ViewListener>>
        }

    }

    class Main <<system>>{
        + {static} main(args: String[])
    }
}

WindowScreen <|-- StartScreen
WindowScreen <|-- ChoiceScreen

Weapon <|-- Knife
Weapon <|-- LongSword

Main --> MainWindowController

MainWindowController -> MainWindow

MainWindow *--> WindowScreen

StartButtonListener <- StartScreen
MainWindowController <-- StartButtonListener

ChoiceScreen <- ChoiceScreenController
ChoiceScreen --> ChoiceButtonListener
ChoiceScreenController <-- ChoiceButtonListener
ChoiceScreenController ---> PlayerManager
ChoiceScreenController ---> StoryManager


PlayerManager --> Player

Player *--> Weapon

StoryManager *--> Story

@enduml
